# -*- coding: utf-8 -*-
"""kadyrova_7_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IzTegR1ogpWAfnNIi5KU4B5DrfwOFKzg
"""

def check_input(element):
    """
    Проверяет, является ли элемент строкой.
    """
    return isinstance(element, str)


def get_substring(s):
    """
    Находит и возвращает самую длинную подстроку без повторяющихся символов.
    Если таких подстрок несколько, возвращает первую.
    """
    start = 0
    max_len = 0
    max_substr = ""
    used_chars = {}

    for i, char in enumerate(s):
        if char in used_chars and used_chars[char] >= start:
            start = used_chars[char] + 1
        used_chars[char] = i
        if i - start + 1 > max_len:
            max_len = i - start + 1
            max_substr = s[start:i+1]

    return max_substr


def main(lst):
    """
    Находит самую длинную строку в списке, затем самую длинную подстроку без повторов.
    Печатает индекс строки и подстроку.
    """
    max_len = -1
    max_index = -1
    max_string = ""

    for idx, elem in enumerate(lst):
        if check_input(elem):
            if len(elem) > max_len:
                max_len = len(elem)
                max_index = idx
                max_string = elem

    if max_index == -1:
        print(-1, "''")
    else:
        substr = get_substring(max_string)
        print(f"{max_index}, '{substr}'")


example_list = [[0, 4, 8], 'abca', 7, 'aaaaa']
main(example_list)